// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RssFeeder.Contexts;

#nullable disable

namespace RssFeeder.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230619182511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RssFeeder.Models.IdentityUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("IdentityUsers");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("921eac24-b306-4c5e-95b9-56b71feea6ae"),
                            Login = "Admin",
                            Password = "Admin",
                            Role = "admin"
                        },
                        new
                        {
                            UserId = new Guid("6e1b8139-e6f2-47ae-8fed-401b6e46b192"),
                            Login = "User",
                            Password = "User",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("RssFeeder.Models.IdentityUserRssItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Readed");
                });

            modelBuilder.Entity("RssFeeder.Models.RssItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DbAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PubDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("RssFeeder.Models.IdentityUserRssItem", b =>
                {
                    b.HasOne("RssFeeder.Models.RssItem", "RssItem")
                        .WithMany("UsersRssItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RssFeeder.Models.IdentityUser", "User")
                        .WithMany("UsersRssItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RssItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RssFeeder.Models.IdentityUser", b =>
                {
                    b.Navigation("UsersRssItems");
                });

            modelBuilder.Entity("RssFeeder.Models.RssItem", b =>
                {
                    b.Navigation("UsersRssItems");
                });
#pragma warning restore 612, 618
        }
    }
}
